"""Rename document fields

Revision ID: 4418465d2df7
Revises: 0bf5e14685c3
Create Date: 2018-05-27 13:23:48.864445

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4418465d2df7'
down_revision = '0bf5e14685c3'
branch_labels = None
depends_on = None

def rename_column(batch_op, old_name, new_name):
    batch_op.alter_column(old_name, new_column_name=new_name)


def upgrade():
    with op.batch_alter_table('documentos') as doc:
        rename_column(doc, 'cliente_direccion', 'customer_address')
        rename_column(doc, 'cliente_cuit', 'customer_cuit')
        rename_column(doc, 'cliente_id', 'customer_id')
        rename_column(doc, 'cliente_nombre', 'customer_name')
        rename_column(doc, 'descuento', 'discount')
        rename_column(doc, 'tipo', 'doc_type')
        rename_column(doc, 'periodo_iva', 'fiscal_period')
        rename_column(doc, 'fecha', 'issue_date')
        rename_column(doc, 'hora', 'issue_time')
        rename_column(doc, 'neto', 'net')
        rename_column(doc, 'numero', 'number')
        rename_column(doc, 'vendedor', 'salesman')

        doc.create_index(op.f('ix_documentos_customer_id'), ['customer_id'])
        doc.drop_index('ix_documentos_cliente_id')

        doc.create_unique_constraint(None, ['doc_type', 'issue_date', 'number'])
        doc.drop_constraint('documentos_tipo_key', type_='unique')

        doc.drop_constraint('documentos_cliente_id_fkey', type_='foreignkey')
        doc.create_foreign_key(None, 'clientes', ['customer_id'], ['id'])



    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_index(op.f('ix_documentos_customer_id'), 'documentos', ['customer_id'], unique=False)
    # op.drop_index('ix_documentos_cliente_id', table_name='documentos')

    # op.drop_constraint('documentos_tipo_key', 'documentos', type_='unique')
    # op.create_unique_constraint(None, 'documentos', ['doc_type', 'issue_date', 'number'])

    # op.drop_constraint('documentos_cliente_id_fkey', 'documentos', type_='foreignkey')
    # op.create_foreign_key(None, 'documentos', 'clientes', ['customer_id'], ['id'])

    # op.add_column('documentos', sa.Column('customer_address', sa.UnicodeText(length=60), nullable=True))
    # op.add_column('documentos', sa.Column('customer_cuit', sa.UnicodeText(length=13), nullable=True))
    # op.add_column('documentos', sa.Column('customer_id', sa.Integer(), nullable=False))
    # op.add_column('documentos', sa.Column('customer_name', sa.UnicodeText(length=35), nullable=True))
    # op.add_column('documentos', sa.Column('discount', sa.Numeric(precision=10, scale=2), nullable=True))
    # op.add_column('documentos', sa.Column('doc_type', sa.Unicode(length=3), nullable=False))
    # op.add_column('documentos', sa.Column('fiscal_period', sa.Date(), nullable=True))
    # op.add_column('documentos', sa.Column('issue_date', sa.Date(), nullable=False))
    # op.add_column('documentos', sa.Column('issue_time', sa.Time(), nullable=True))
    # op.add_column('documentos', sa.Column('net', sa.Numeric(precision=10, scale=2), nullable=False))
    # op.add_column('documentos', sa.Column('number', sa.Integer(), nullable=True))
    # op.add_column('documentos', sa.Column('salesman', sa.UnicodeText(length=3), nullable=True))

    # op.drop_column('documentos', 'periodo_iva')
    # op.drop_column('documentos', 'numero')
    # op.drop_column('documentos', 'cliente_nombre')
    # op.drop_column('documentos', 'cliente_direccion')
    # op.drop_column('documentos', 'descuento')
    # op.drop_column('documentos', 'hora')
    # op.drop_column('documentos', 'tipo')
    # op.drop_column('documentos', 'fecha')
    # op.drop_column('documentos', 'vendedor')
    # op.drop_column('documentos', 'cliente_cuit')
    # op.drop_column('documentos', 'cliente_id')
    # op.drop_column('documentos', 'neto')
    # ### end Alembic commands ###


def downgrade():

    with op.batch_alter_table('documentos') as doc:
        rename_column(doc, 'customer_address', 'cliente_direccion')
        rename_column(doc, 'customer_cuit', 'cliente_cuit')
        rename_column(doc, 'customer_id', 'cliente_id')
        rename_column(doc, 'customer_name', 'cliente_nombre')
        rename_column(doc, 'discount', 'descuento')
        rename_column(doc, 'doc_type', 'tipo')
        rename_column(doc, 'fiscal_period', 'periodo_iva')
        rename_column(doc, 'issue_date', 'fecha')
        rename_column(doc, 'issue_time', 'hora')
        rename_column(doc, 'net', 'neto')
        rename_column(doc, 'number', 'numero')
        rename_column(doc, 'salesman', 'vendedor')

        doc.drop_constraint('documentos_customer_id_fkey', type_='foreignkey')
        doc.create_foreign_key('documentos_cliente_id_fkey', 'clientes', ['cliente_id'], ['id'])

        doc.create_index('ix_documentos_cliente_id', ['cliente_id'], unique=False)
        doc.drop_index(op.f('ix_documentos_customer_id'))

        doc.drop_constraint('documentos_doc_type_issue_date_number_key', type_='unique')
        doc.create_unique_constraint('documentos_tipo_key', ['tipo', 'fecha', 'numero'])


    # op.drop_constraint(None, 'documentos', type_='foreignkey')
    # op.create_foreign_key('documentos_cliente_id_fkey', 'documentos', 'clientes', ['cliente_id'], ['id'])
    # op.drop_constraint(None, 'documentos', type_='unique')
    # op.create_index('ix_documentos_cliente_id', 'documentos', ['cliente_id'], unique=False)
    # op.create_unique_constraint('documentos_tipo_key', 'documentos', ['tipo', 'fecha', 'numero'])
    # op.drop_index(op.f('ix_documentos_customer_id'), table_name='documentos')

    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('documentos', sa.Column('neto', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    # op.add_column('documentos', sa.Column('cliente_id', sa.INTEGER(), autoincrement=False, nullable=False))
    # op.add_column('documentos', sa.Column('cliente_cuit', sa.TEXT(), autoincrement=False, nullable=True))
    # op.add_column('documentos', sa.Column('vendedor', sa.TEXT(), autoincrement=False, nullable=True))
    # op.add_column('documentos', sa.Column('fecha', sa.DATE(), autoincrement=False, nullable=False))
    # op.add_column('documentos', sa.Column('tipo', sa.VARCHAR(length=3), autoincrement=False, nullable=False))
    # op.add_column('documentos', sa.Column('hora', postgresql.TIME(), autoincrement=False, nullable=True))
    # op.add_column('documentos', sa.Column('descuento', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    # op.add_column('documentos', sa.Column('cliente_direccion', sa.TEXT(), autoincrement=False, nullable=True))
    # op.add_column('documentos', sa.Column('cliente_nombre', sa.TEXT(), autoincrement=False, nullable=True))
    # op.add_column('documentos', sa.Column('numero', sa.INTEGER(), autoincrement=False, nullable=True))
    # op.add_column('documentos', sa.Column('periodo_iva', sa.DATE(), autoincrement=False, nullable=True))
    # op.drop_column('documentos', 'salesman')
    # op.drop_column('documentos', 'number')
    # op.drop_column('documentos', 'net')
    # op.drop_column('documentos', 'issue_time')
    # op.drop_column('documentos', 'issue_date')
    # op.drop_column('documentos', 'fiscal_period')
    # op.drop_column('documentos', 'doc_type')
    # op.drop_column('documentos', 'discount')
    # op.drop_column('documentos', 'customer_name')
    # op.drop_column('documentos', 'customer_id')
    # op.drop_column('documentos', 'customer_cuit')
    # op.drop_column('documentos', 'customer_address')
    # ### end Alembic commands ###
