"""Rename items table and fields

Revision ID: 7a699b427893
Revises: 87b01a87c6da
Create Date: 2018-05-31 02:17:31.492672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a699b427893'
down_revision = '87b01a87c6da'
branch_labels = None
depends_on = None


def rename_column(batch_op, old_name, new_name):
    batch_op.alter_column(old_name, new_column_name=new_name)


def upgrade():
    op.rename_table('items_documento', 'item')

    with op.batch_alter_table('item') as it:
        rename_column(it, 'codigo', 'sku')
        rename_column(it, 'descripcion', 'description')
        rename_column(it, 'cantidad', 'quantity')
        rename_column(it, 'precio', 'price')
        rename_column(it, 'articulo_id', 'product_id')
        rename_column(it, 'documento_id', 'document_id')

    op.execute('ALTER SEQUENCE items_documento_id_seq RENAME TO item_id_seq')
    op.execute('ALTER INDEX items_documento_pkey RENAME TO item_pkey')
    op.execute('ALTER INDEX ix_items_documento_articulo_id RENAME TO ix_item_product_id')
    op.execute('ALTER INDEX ix_items_documento_documento_id RENAME TO ix_item_document_id')
    op.execute('ALTER TABLE item RENAME CONSTRAINT items_documento_articulo_id_fkey TO item_product_id_fkey')
    op.execute('ALTER TABLE item RENAME CONSTRAINT items_documento_documento_id_fkey TO item_document_id_fkey')

    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('item',
    #     sa.Column('id', sa.Integer(), nullable=False),
    #     sa.Column('sku', sa.UnicodeText(length=14), nullable=True),
    #     sa.Column('description', sa.UnicodeText(length=40), nullable=False),
    #     sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    #     sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    #     sa.Column('product_id', sa.Integer(), nullable=True),
    #     sa.Column('document_id', sa.Integer(), nullable=False),
    #     sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    #     sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    #     sa.PrimaryKeyConstraint('id')
    # )
    # op.create_index(op.f('ix_item_document_id'), 'item', ['document_id'], unique=False)
    # op.create_index(op.f('ix_item_product_id'), 'item', ['product_id'], unique=False)
    # op.drop_index('ix_items_documento_articulo_id', table_name='items_documento')
    # op.drop_index('ix_items_documento_documento_id', table_name='items_documento')
    # op.drop_table('items_documento')
    # ### end Alembic commands ###


def downgrade():
    op.rename_table('item', 'items_documento')

    with op.batch_alter_table('items_documento') as it:
        rename_column(it, 'sku', 'codigo')
        rename_column(it, 'description', 'descripcion')
        rename_column(it, 'quantity', 'cantidad')
        rename_column(it, 'price', 'precio')
        rename_column(it, 'product_id', 'articulo_id')
        rename_column(it, 'document_id', 'documento_id')

    op.execute('ALTER SEQUENCE item_id_seq RENAME TO items_documento_id_seq')
    op.execute('ALTER INDEX item_pkey RENAME TO items_documento_pkey')
    op.execute('ALTER INDEX ix_item_product_id RENAME TO ix_items_documento_articulo_id')
    op.execute('ALTER INDEX ix_item_document_id RENAME TO ix_items_documento_documento_id')
    op.execute('ALTER TABLE items_documento RENAME CONSTRAINT item_product_id_fkey TO items_documento_articulo_id_fkey')
    op.execute('ALTER TABLE items_documento RENAME CONSTRAINT item_document_id_fkey TO items_documento_documento_id_fkey')


    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('items_documento',
    #     sa.Column('id', sa.INTEGER(), nullable=False),
    #     sa.Column('codigo', sa.TEXT(), autoincrement=False, nullable=True),
    #     sa.Column('descripcion', sa.TEXT(), autoincrement=False, nullable=False),
    #     sa.Column('cantidad', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    #     sa.Column('precio', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    #     sa.Column('articulo_id', sa.INTEGER(), autoincrement=False, nullable=True),
    #     sa.Column('documento_id', sa.INTEGER(), autoincrement=False, nullable=False),
    #     sa.ForeignKeyConstraint(['articulo_id'], ['product.id'], name='items_documento_articulo_id_fkey'),
    #     sa.ForeignKeyConstraint(['documento_id'], ['document.id'], name='items_documento_documento_id_fkey'),
    #     sa.PrimaryKeyConstraint('id', name='items_documento_pkey')
    # )
    # op.create_index('ix_items_documento_documento_id', 'items_documento', ['documento_id'], unique=False)
    # op.create_index('ix_items_documento_articulo_id', 'items_documento', ['articulo_id'], unique=False)
    # op.drop_index(op.f('ix_item_product_id'), table_name='item')
    # op.drop_index(op.f('ix_item_document_id'), table_name='item')
    # op.drop_table('item')
    # ### end Alembic commands ###
